### ISSUE TITLE
Namalsk 

### ISSUE THREAD

**Issue by jus61** [macchky/MAC_A3Wasteland.Altis#2]
Will you adjust the for me on the map Namalsk for a donation?

https://forums.bistudio.com/topic/188868-namalsk-for-arma-3/

**Comment by macchky** [comment]
Sorry, I don't like Namalsk. But I may create for Bozcaada in near future.

https://forums.bistudio.com/topic/185022-map-bozcaada/

**Comment by jus61** [comment]
Ok I would be interested also.

And Stratis?

**Comment by macchky** [comment]
Stratis mission already exists. Search github
